---
abstract: 'A Template Plugin To Use DateTime Objects'
author:
  - 'Copyright (c) 2004-2007 Daisuke Maki <daisuke@endeworks.jp>.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-DateTime
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  DateTime::Format::Strptime: 0
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06002
