---
name: Template-Plugin-DateTime
version: 0.03
author:
  - Copyright (c) 2004-3005 Daisuke Maki E<lt>dmaki@cpan.orgE<gt>. All rights reserved.
abstract: A Template Plugin To Use DateTime Objects
license: perl
requires:
  DateTime: 0
  Template: 0
recommends:
  perl: 5.6.1
build_requires:
  Test::More: 0
provides:
  Template::Plugin::DateTime:
    file: lib/Template/Plugin/DateTime.pm
    version: 0.03
generated_by: Module::Build version 0.2611
